### ISSUE TITLE
Missing CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by carlagesa** [PlotiHub/Plotihub-App#32]
## Missing CODE_OF_CONDUCT.md file

**Description:**
The repository currently lacks a `CODE_OF_CONDUCT.md` file. This file is essential for establishing guidelines for community behavior and ensuring a welcoming and inclusive environment for all contributors.

**Solution:**
Add a `CODE_OF_CONDUCT.md` file to the repository root with a suitable code of conduct. The [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) is a popular choice.

**Tasks:**
1. Research and select an appropriate code of conduct.
2. Create a `CODE_OF_CONDUCT.md` file in the root of the repository.
3. Add the selected code of conduct to the file.
4. Commit the changes and push to the repository while adhering to the `CONTRIBUTOR GUIDELINES` .

**Additional Resources:**
- [GitHub Help: Adding a code of conduct to your project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

**Comment by SeanAverS** [comment]
Hi, 

I'm interested on working on this. Could I please be assigned? Thanks.
